### ISSUE TITLE
Update React version and refactor

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Example-Flask-React-SocketIO#5]

**Comment by VinayakBagaria** [comment]
Taking this.

**Comment by VinayakBagaria** [comment]
Setup issue - no module named events referenced from [app/__init__.py](https://github.com/CharlyJazz/Flask-React-SocketIO/blob/master/app/__init__.py#L1)

**Comment by CharlyJazz** [comment]
Wow, thats true!

The module socketio it is not in the requirements.txt file

You could solve that, and create a PR

**Comment by CharlyJazz** [comment]
#12

**Comment by JoshieKun** [comment]
Taking this! :pouting_cat:
